name: mobile_uploader
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Para selecionar imagens da galeria (simulando "tirar foto")
  image_picker: ^1.0.8 
  
  # Para fazer requisições HTTP
  http: ^1.2.1 
  
  # Para lidar com caminhos de arquivo (opcional, mas útil)
  path: ^1.8.3
  cross_file: ^0.3.5+1

  # Necessário para usar MediaType no upload via bytes (solução Web)
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

